---
language: cpp
os: linux
dist: bionic

jobs:
  include:
    - env:
        - CXX=g++
      before_install:
        # We need to ensure the cmake config for UnitTest++ is installed properly,
        # because the folks at ubuntu don't include the cmake files.
        # We use the system compiler to mimic the OS package.
        - mkdir /tmp/unit_test_plus_plus
        - pushd /tmp/unit_test_plus_plus
        - wget -O /tmp/unittest-cpp-v2.0.0.tar.gz https://github.com/unittest-cpp/unittest-cpp/archive/v2.0.0.tar.gz
        - tar zxf /tmp/unittest-cpp-v2.0.0.tar.gz
        - mkdir build
        - cd build
        - env -u CXX cmake ../unittest-cpp-2.0.0 && make && sudo make install
        - popd
    - env:
        - CXX=clang++
      before_install:
        # We need to ensure the cmake config for UnitTest++ is installed properly,
        # because the folks at ubuntu don't include the cmake files.
        # We use the system compiler to mimic the OS package.
        - mkdir /tmp/unit_test_plus_plus
        - pushd /tmp/unit_test_plus_plus
        - wget -O /tmp/unittest-cpp-v2.0.0.tar.gz https://github.com/unittest-cpp/unittest-cpp/archive/v2.0.0.tar.gz
        - tar zxf /tmp/unittest-cpp-v2.0.0.tar.gz
        - mkdir build
        - cd build
        - env -u CXX cmake ../unittest-cpp-2.0.0 && make && sudo make install
        - popd

    - os: osx
      osx_image: xcode9.4
      before_install:
        # The homebrew package suffers from the same shortcoming as the linux one:
        # it is missing the cmake files.
        # Just force it manually.
        - mkdir /tmp/unit_test_plus_plus
        - pushd /tmp/unit_test_plus_plus
        - wget -O /tmp/unittest-cpp-v2.0.0.tar.gz https://github.com/unittest-cpp/unittest-cpp/archive/v2.0.0.tar.gz
        - tar zxf /tmp/unittest-cpp-v2.0.0.tar.gz
        - mkdir build
        - cd build
        - env -u CXX cmake ../unittest-cpp-2.0.0 && make && sudo make install
        - popd

before_script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build

script:
  - cmake ..
  - make
  - make test
