---
language: cpp
os: linux
dist: bionic

jobs:
  include:
    - addons:
        apt:
          packages:
            - libboost-all-dev
      env:
         - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  # We need to ensure the cmake config for UnitTest++ is installed properly,
  # because the folks at ubuntu don't.
  - mkdir /tmp/unit_test_plus_plus
  - pushd /tmp/unit_test_plus_plus
  - wget -O /tmp/unittest-cpp-v2.0.0.tar.gz https://github.com/unittest-cpp/unittest-cpp/archive/v2.0.0.tar.gz
  - tar zxf /tmp/unittest-cpp-v2.0.0.tar.gz
  - mkdir build
  - cd build
  - cmake ../unittest-cpp-2.0.0 && make && sudo make install
  - popd

  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - cmake ..

script:
  - make
  - make test
